sudo: false

language: node_js
node_js:
  - node 

script: 
  - npm run test:coveralls

notifications:
  email: false

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage